apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dataviz-api
  name: dataviz-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dataviz-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dataviz-api
    spec:
      containers:
      - image: kxkaro/dataviz-server
        imagePullPolicy: "Always"
        name: dataviz-api
        ports:
        - containerPort: 5000
        resources: {}
      # - env:
      #   - name: DATABASE_URL
      #     valueFrom:
      #       secretKeyRef:
      #         name: mongo-secret
      #         key: DATABASE_URL
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
