steps:
  # running docker-compose
  - name: 'docker/compose:1.26.2'
    args: ['up', '-d']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dataviz-286409/dataviz']