steps:
  # running docker-compose
- name: 'docker/compose:1.26.2'
  args: ['build']
  # Push the container image to Container Registry
- name: 'docker/compose:1.26.2'
  args: ['push']
  #Deploy container image to Cloud Run
images:
  - gcr.io/dataviz-289409/client
  - gcr.io/dataviz-289409/server

# https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-cloud-run
#   steps:
# # Build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/PROJECT_ID/IMAGE', '.']
# # Push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/PROJECT_ID/IMAGE']
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'SERVICE-NAME', '--image', 'gcr.io/PROJECT_ID/IMAGE', '--region', 'REGION', '--platform', 'managed']
# images:
# - gcr.io/PROJECT_ID/IMAGE