version: '3'
services:
  dataviz-web:
    image: kxkaro/dataviz-client
    build: ./client
    restart: always
    ports: 
      - "80:80"
    depends_on: 
      - "dataviz-api"
    stdin_open: true
  dataviz-api:
    image: kxkaro/dataviz-server
    build: ./server
    restart: always
    expose:
      - "5000"
