version: '3'
services:
  web:
    image: gcr.io/dataviz-289409/client
    build: ./client
    ports: 
      - "3000:80"
    depends_on: 
      - "api"
    stdin_open: true
  api:
    image: gcr.io/dataviz-289409/server
    build: ./server
    expose:
      - "5000"
