apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dataviz-web
  name: dataviz-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dataviz-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: dataviz-web
    spec:
      containers:
      - image: kxkaro/dataviz-client
        imagePullPolicy: "Always"
        name: dataviz-web
        ports:
        - containerPort: 80
        resources: {}
        stdin: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
